format:
  html:
    theme: minty 
    # minty, slate, yeti
    toc: true

project:
  type: website
  output-dir: docs

website:
  title: "Albert Miao"
  navbar:
    search: false
    left:
      - text: About
        href: about/
      - text: Blog
        href: blog/
      - text: Papers
        href: papers/
      - text: Projects
        href: projects/
    right:
      - icon: github
        href: https://github.com/YOUR_USERNAME

